cleric_spells = [
    {"name": "Aid", "level": 2, "source": "PHB 2014", "classes": ["Cleric", "Paladin"]},
    {"name": "Animate Dead", "level": 3, "source": "PHB 2014", "classes": ["Cleric", "Wizard"]},
    {"name": "Augury", "level": 2, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Aura of Vitality", "level": 3, "source": "PHB 2014", "classes": ["Paladin", "Cleric (TCoE)"]},
    {"name": "Bane", "level": 1, "source": "PHB 2014", "classes": ["Bard", "Cleric"]},
    {"name": "Beacon of Hope", "level": 3, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Bestow Curse", "level": 3, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Wizard"]},
    {"name": "Bless", "level": 1, "source": "PHB 2014", "classes": ["Cleric", "Paladin"]},
    {"name": "Blindness/Deafness", "level": 2, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Sorcerer", "Wizard"]},
    {"name": "Calm Emotions", "level": 2, "source": "PHB 2014", "classes": ["Bard", "Cleric"]},
    {"name": "Ceremony", "level": 1, "source": "XGtE", "classes": ["Cleric", "Paladin"]},
    {"name": "Clairvoyance", "level": 3, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Sorcerer", "Wizard"]},
    {"name": "Command", "level": 1, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Paladin"]},
    {"name": "Continual Flame", "level": 2, "source": "PHB 2014", "classes": ["Cleric", "Wizard"]},
    {"name": "Create Food and Water", "level": 3, "source": "PHB 2014", "classes": ["Cleric", "Paladin"]},
    {"name": "Create or Destroy Water", "level": 1, "source": "PHB 2014", "classes": ["Cleric", "Druid"]},
    {"name": "Cure Wounds", "level": 1, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Druid", "Paladin", "Ranger"]},
    {"name": "Daylight", "level": 3, "source": "PHB 2014", "classes": ["Cleric", "Druid", "Paladin", "Ranger"]},
    {"name": "Detect Evil and Good", "level": 1, "source": "PHB 2014", "classes": ["Cleric", "Paladin"]},
    {"name": "Detect Magic", "level": 1, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Wizard"]},
    {"name": "Detect Poison and Disease", "level": 1, "source": "PHB 2014", "classes": ["Cleric", "Druid", "Paladin", "Ranger"]},
    {"name": "Dispel Magic", "level": 3, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Druid", "Paladin", "Sorcerer", "Warlock", "Wizard"]},
    {"name": "Enhance Ability", "level": 2, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Druid", "Sorcerer"]},
    {"name": "Feign Death", "level": 3, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Druid", "Wizard"]},
    {"name": "Find Traps", "level": 2, "source": "PHB 2014", "classes": ["Cleric", "Druid", "Ranger"]},
    {"name": "Gentle Repose", "level": 2, "source": "PHB 2014", "classes": ["Cleric", "Wizard"]},
    {"name": "Glyph of Warding", "level": 3, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Wizard"]},
    {"name": "Guidance", "level": 0, "source": "PHB 2014", "classes": ["Cleric", "Druid"]},
    {"name": "Guiding Bolt", "level": 1, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Healing Word", "level": 1, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Druid"]},
    {"name": "Hold Person", "level": 2, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"]},
    {"name": "Inflict Wounds", "level": 1, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Lesser Restoration", "level": 2, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Druid", "Paladin", "Ranger"]},
    {"name": "Life Transference", "level": 3, "source": "XGtE", "classes": ["Cleric", "Wizard"]},
    {"name": "Light", "level": 0, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Sorcerer", "Wizard"]},
    {"name": "Locate Object", "level": 2, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"]},
    {"name": "Magic Circle", "level": 3, "source": "PHB 2014", "classes": ["Cleric", "Paladin", "Warlock", "Wizard"]},
    {"name": "Mass Healing Word", "level": 3, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Meld into Stone", "level": 3, "source": "PHB 2014", "classes": ["Cleric", "Druid"]},
    {"name": "Mending", "level": 0, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Druid", "Sorcerer", "Wizard"]},
    {"name": "Prayer of Healing", "level": 2, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Protection from Energy", "level": 3, "source": "PHB 2014", "classes": ["Cleric", "Druid", "Ranger", "Sorcerer", "Wizard"]},
    {"name": "Protection from Evil and Good", "level": 1, "source": "PHB 2014", "classes": ["Cleric", "Paladin", "Warlock", "Wizard"]},
    {"name": "Protection from Poison", "level": 2, "source": "PHB 2014", "classes": ["Cleric", "Druid", "Paladin", "Ranger"]},
    {"name": "Purify Food and Drink", "level": 1, "source": "PHB 2014", "classes": ["Cleric", "Druid", "Paladin"]},
    {"name": "Remove Curse", "level": 3, "source": "PHB 2014", "classes": ["Cleric", "Paladin", "Warlock", "Wizard"]},
    {"name": "Resistance", "level": 0, "source": "PHB 2014", "classes": ["Cleric", "Druid"]},
    {"name": "Revivify", "level": 3, "source": "PHB 2014", "classes": ["Cleric", "Paladin"]},
    {"name": "Sacred Flame", "level": 0, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Sanctuary", "level": 1, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Sending", "level": 3, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Wizard"]},
    {"name": "Shield of Faith", "level": 1, "source": "PHB 2014", "classes": ["Cleric", "Paladin"]},
    {"name": "Silence", "level": 2, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Ranger"]},
    {"name": "Spare the Dying", "level": 0, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Speak with Dead", "level": 3, "source": "PHB 2014", "classes": ["Bard", "Cleric"]},
    {"name": "Spirit Guardians", "level": 3, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Spirit Shroud", "level": 3, "source": "TCoE", "classes": ["Cleric", "Paladin", "Warlock", "Wizard"]},
    {"name": "Spiritual Weapon", "level": 2, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Thaumaturgy", "level": 0, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Toll the Dead", "level": 0, "source": "XGtE", "classes": ["Cleric", "Warlock", "Wizard"]},
    {"name": "Tongues", "level": 3, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"]},
    {"name": "Warding Bond", "level": 2, "source": "PHB 2014", "classes": ["Cleric"]},
    {"name": "Water Walk", "level": 3, "source": "PHB 2014", "classes": ["Cleric", "Druid", "Ranger", "Sorcerer"]},
    {"name": "Word of Radiance", "level": 0, "source": "XGtE", "classes": ["Cleric"]},
    {"name": "Zone of Truth", "level": 2, "source": "PHB 2014", "classes": ["Bard", "Cleric", "Paladin"]}
]